### ISSUE TITLE
Possible bug when parsing a float with more than one decimal

### ISSUE THREAD

**Issue by Fonz001** [trenskow/isvalid.js#3]
Hi!

It seems that the number: "5.0535017175947585" (String) does not get validated as a Number, the regex: /^[0-9]+(?:\.[0.9])?$/ seems to only parse one decimal (source: regex101.com)

A possible fix could be: ^[0-9]+(?:\.[0-9]*)?$  , although I must say i'm not an expert at regular expressions.

Greetings!

**Comment by Fonz001** [comment]
A better regex can be found here: http://ntt.cc/2008/05/10/over-10-useful-javascript-regular-expression-functions-to-improve-your-web-applications-efficiency.html (negative numbers als well)

**Comment by trenskow** [comment]
Thanks @Fonz001. This is definitely a bug. I'll fix that ...

**Comment by trenskow** [comment]
Fixed in 34af404f97c8b2b1840540f168b5c1048da5f220
