### ISSUE TITLE
obj.constructor not always set

### ISSUE THREAD

**Issue by Fonz001** [trenskow/isvalid.js#4]
Hi again!

It seems that in some rare cases the obj.construtor is undefined (validate.js:18)

Reference: http://javascript.info/tutorial/constructor

The 'typeof' approach might be a better solution.

**Comment by trenskow** [comment]
Once again thanks! I agree - `typeof` is better...

**Comment by trenskow** [comment]
Fixed in 7b478815b20ac6646fbff62f78be72b45c0f4117

**Comment by trenskow** [comment]
Even though I closed this I have kept constructor.name in the finalizer so far. The validator has been updated to using typeof. That is, because ex. `typeof RegExp` returns `'object'` - so I just need to figure out how to restructure myself out of it.

**Comment by trenskow** [comment]
And then again. In the finalizer I know which objects are expected - so the non-constructor.name might not be so much of an issue there.

**Comment by trenskow** [comment]
Then again it was used in both the ranges.js and unique.js files.
