### ISSUE TITLE
Use custom validators as additional validation steps alongside type and other validators.

### ISSUE THREAD

**Issue by mikidep** [trenskow/isvalid.js#5]
I will report my use case: suppose I have to validate a query object that has, among the others, the parameters `fromDate` and `toDate`, and I need to be sure that they are chronologically coherent. Why should I write two different schemas and chain validations in order to achieve that? Wouldn't it make more sense for me to specify a `schema:` validator *and* a `custom:` one? What if I wanted to validate an object checking its type *and* its conformance to some custom requirements of mine?

**Comment by trenskow** [comment]
Sorry for not getting back on this. This is an interesting suggestion. I assume, then, that the custom validator should get called after the validator has validated the data? That would make most sense, wouldn't it?

**Comment by mikidep** [comment]
Yes, that is the way I thought it, the custom validator would add specialization to the others.

**Comment by trenskow** [comment]
Well, I guess I never thought of it that way, but I guess it makes pretty good sense. I only made it so that you were not tied to whatever validation features the module had. I'll take a look at it.
